[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200